name: "Doxygen"
on:
  workflow_dispatch:
  pull_request:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install doxygen and graphviz
      run: sudo apt-get install -y doxygen graphviz
    - name: Run doxygen and check for warnings/errors
      run: |
        ./doxygen/doxygen.sh
