name: Galacitc Binary Build - main
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
    branches:
      - master
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: galacitc
      ros_repo: main
      upstream_workspace: realtime_tools-not-released.galacitc.repos
      ref_for_scheduled_build: master
    secrets:
      SCH_COMMON_KEY: ${{ secrets.SCH_COMMON_KEY }}
