name: Galactic RHEL Binary Build
on:
  workflow_dispatch:
    branches:
      - master
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  galactic_rhel_binary:
    name: Galactic RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: galactic
    container: jaronl/ros:galactic-alma
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/realtime_tools
      - run: |
          rosdep update
          rosdep install -iy --from-path src/realtime_tools
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
