name: Humble Semi-Binary Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
  pull_request: &event
    branches:
      - humble
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/humble-semi-binary-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'realtime_tools.humble.repos'
      - '**.xml'
  push: *event
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: humble
      ros_repo: testing
      ref_for_scheduled_build: humble
      upstream_workspace: realtime_tools.humble.repos
  binary_clang:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: humble
      ros_repo: testing
      ref_for_scheduled_build: humble
      upstream_workspace: realtime_tools.humble.repos
      additional_debs: clang
      c_compiler: clang
      cxx_compiler: clang++
      not_test_build: true
