name: Humble Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - humble
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * MON-FRI'

jobs:
  source:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ref: humble
      os_name: ${{ matrix.OS_NAME }}
      container: ${{ matrix.CONTAINER }}
