name: Humble Coverage Build
on:
  workflow_dispatch:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

concurrency:
  # cancel previous runs of the same workflow, except for pushes on humble branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, '/refs/heads') }}

jobs:
  coverage:
    name: coverage build
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@master
    secrets: inherit
    with:
      ros_distro: humble
