name: RHEL Iron Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'


jobs:
  iron_rhel_binary:
    name: Iron RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: iron
    container: ghcr.io/ros-controls/ros:iron-rhel
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/realtime_tools
      - name: Install dependencies
        run: |
          rosdep update
          rosdep install -iyr --from-path src/realtime_tools || true
      - name: Build and test
        run: |
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
          colcon test-result --verbose
