name: Rolling RHEL Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  iron_rhel_binary:
    name: Iron RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: iron
    container: ghcr.io/ros-controls/ros:${{ env.ROS_DISTRO }}-rhel
    steps:
      - uses: actions/checkout@v3
        with:
          path: src/realtime_tools
      - run: |
          rosdep update
          rosdep install -iy --from-path src/realtime_tools
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
