name: Jazzy RHEL Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - jazzy
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on jazzy branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, '/refs/heads') }}

jobs:
  rhel_semi_binary_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-rhel-binary-build.yml@master
    with:
      ros_distro: jazzy
      ref_for_scheduled_build: jazzy
