name: Rolling Coverage Build
on:
  workflow_dispatch:
  pull_request: &event
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/rolling-coverage-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - '**.xml'
  push: *event

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  coverage:
    name: coverage build
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-build-coverage.yml@master
    secrets: inherit
    with:
      ros_distro: rolling
