name: Rolling Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * MON-FRI'

jobs:
  source:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [kilted, rolling]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ref: master
      os_name: ubuntu-latest
      container: ubuntu:24.04
