name: rosdoc2

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - doc/**
      - rosdoc2.yaml
      - package.xml


jobs:
  check:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-rosdoc2.yml@master
